{% set version = "0.2.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-gfonts
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gfonts_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gfonts/gfonts_{{ version }}.tar.gz
  sha256: b970a877ee5a1b530aa6936309f7d81670ee8caf429c7b778755d8d7e8708dec

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-crayon
    - r-crul
    - r-glue
    - r-htmltools
    - r-jsonlite
    - r-shiny
  run:
    - r-base
    - r-crayon
    - r-crul
    - r-glue
    - r-htmltools
    - r-jsonlite
    - r-shiny

test:
  commands:
    - $R -e "library('gfonts')"           # [not win]
    - "\"%R%\" -e \"library('gfonts')\""  # [win]

about:
  home: https://dreamrs.github.io/gfonts/, https://github.com/dreamRs/gfonts
  license: GPL-3.0-only
  summary: Download 'Google' fonts and generate 'CSS' to use in 'rmarkdown' documents and 'shiny' applications. Some popular fonts are included and ready to use.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
